server:
  port: 8601
spring:
  application:
    name: user
#  cloud:
#    consul:
#      port: 8500
#      host: 127.0.0.1
#      discovery:
#        service-name: user
#        instance-id: ${spring.application.name}:${spring.cloud.consul.host}:${server.port}
#        health-check-path: /actuator/health
#        health-check-interval: 10s
#        prefer-ip-address: true
#        heartbeat:
#          enabled: true